apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web  # Nome do Deployment
  minReplicas: 1  # Mínimo de 1 réplica
  maxReplicas: 5  # Máximo de 5 réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu  # Métrica baseada no uso de CPU
      target:
        type: Utilization
        averageUtilization: 60  # Alvo de 60% de utilização da CPU